/**
*  Description     :  This class is for uses of different methods in string.
*
*  Created By      :  Sudarshan singh
*
*  Created Date    :  02/02/2022
*
*  Revision Logs   :  V1.0 - Created - Sudarshan Singh 
*
**/
public with sharing class StringClass {

    /**
    * 
    *   @description    :   In this method describe uses of bydefault methods of string. 
    *
    *   @args           :   None
    *
    *   @return         :   void
    *
    *   @revision Log   :   V1.1 - Created  - 02/02/2022 - Sudarshan singh - Comment
    * 
    **/
    public static void stringClassMethod(){
        //
    }
    
}