<?xml version="1.0" encoding="UTF-8"?>
<Workflow xmlns="http://soap.sforce.com/2006/04/metadata">
    <fieldUpdates>
        <fullName>FU_Entity_Update_EAB</fullName>
        <field>Entity__c</field>
        <literalValue>EAB</literalValue>
        <name>FU_Entity_Update_EAB</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
        <reevaluateOnChange>false</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>FU_Entity_Update_HC</fullName>
        <field>Entity__c</field>
        <literalValue>HC</literalValue>
        <name>FU_Entity_Update_HC</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
        <reevaluateOnChange>false</reevaluateOnChange>
    </fieldUpdates>
    <rules>
        <fullName>WF_Validate_Entity_EAB</fullName>
        <actions>
            <name>FU_Entity_Update_EAB</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>Advisory_Twitter_Feed__c.Applicable_For__c</field>
            <operation>equals</operation>
            <value>EAB.com</value>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
    <rules>
        <fullName>WF_Validate_Entity_HC</fullName>
        <actions>
            <name>FU_Entity_Update_HC</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>Advisory_Twitter_Feed__c.Applicable_For__c</field>
            <operation>equals</operation>
            <value>Advisory.com</value>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
</Workflow>
